myapp/recipe_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class RecipePostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')

myapp/core/views.py
# core/views.py 

from flask import render_template, request, Blueprint
from myapp.models import RecipePost

core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    recipe_posts = RecipePost.query.order_by(RecipePost.date.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', recipe_posts=recipe_posts)

@core.route('/info')
def info():
    return render_template('info.html')

myapp/recipe_posts/views.py
#recipeposts/views 

from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from myapp import db 
from myapp.models import RecipePost
from myapp.recipe_posts.forms import RecipePostForm

recipe_posts = Blueprint('recipe_posts', __name__) # register this in __Init__ py 

# Create a recipe 

@recipe_posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_recipe():
    form = RecipePostForm()
    if form.validate_on_submit():
        recipe_post = RecipePost(title=form.title.data, text=form.text.data, user_id=current_user.id)
        db.session.add(recipe_post)
        db.session.commit()
        flash('Recipe Created')
        print('Recipe post was created')
        return redirect(url_for('core.index'))
    return render_template('create_recipe.html', form=form)


# view a single post
@recipe_posts.route('/<int:recipe_post_id>') #make sure this is an integer 
def recipe_post(recipe_post_id):
    recipe_post = RecipePost.query.get_or_404(recipe_post_id) # this recipe post id is not a string - we are querying for an int 
    return render_template('recipe_post.html', title=recipe_post.title, date=recipe_post.date, post=recipe_post)


# update a post 

@recipe_posts.route('/<int:recipe_post_id>/update',methods=['GET','POST'])
@login_required
def update(recipe_post_id):
    recipe_post = RecipePost.query.get_or_404(recipe_post_id)

    if recipe_post.author != current_user:
        abort(403)

    form = RecipePostForm()


    if form.validate_on_submit():

        recipe_post.title = form.title.data
        recipe_post.text = form.text.data
        db.session.commit()
        flash('Recipe Updated')
        return redirect(url_for('recipe_posts.recipe_post',recipe_post_id=recipe_post.id))

    elif request.method == 'GET':
        form.title.data = recipe_post.title
        form.text.data = recipe_post.text

    return render_template('create_recipe.html',title='Updating',form=form)


# delete post 
@recipe_posts.route('/<int:recipe_post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(recipe_post_id):

    recipe_post = RecipePost.query.get_or_404(recipe_post_id)
    if recipe_post.author != current_user:
        abort(403)

    db.session.delete(recipe_post)
    db.session.commit()
    flash('Recipe Deleted')
    return redirect(url_for('core.index'))

myapp/users/views.py
from crypt import methods
from operator import methodcaller
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myapp import db
from myapp.models import User, RecipePost
from myapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm

users = Blueprint('users', __name__) # dont forget to register this in __init__.py 


# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for Registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index')) #once the user has logged out we will redirect them back home


#account (update UserForm)
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit(): 
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User account updated!!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('account.html', form=form)

@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    recipe_posts = RecipePost.query.filter_by(author=user).order_by(RecipePost.date.desc()).paginate(page=page, per_page=5) 
    return render_template('user_recipe_posts.html', recipe_posts=recipe_posts, user=user)

myapp/templates/account.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{url_for('static', filename='./styles/login.css')}}"/>
<link rel="stylesheet" href="{{url_for('static', filename='./styles/index.css')}}"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&family=Josefin+Slab:wght@600&display=swap" rel="stylesheet">
<div class="profile-header">
    <div align="center">
        <h1>Welcome to the page for {{current_user.username}}</h1>
    </div>
</div>

<div class="account-form">
    <form method="POST" action="" enctype="multipart/form-data">
        <div class="form-group">
            {{form.hidden_tag()}}
        </div>
        <div class="form-group">
            {{form.username.label(class='form-group')}} 
            {{form.username(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.email.label(class='form-group')}} 
            {{form.email(class='form-control')}}
        </div>

        <div class="form-group">
            {{form.submit(class='btn btn-primary')}}
        </div>


    </form>
</div>
{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{url_for('static', filename='./styles/base.css')}}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&family=Josefin+Slab:wght@600&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22256%22 height=%22256%22 viewBox=%220 0 100 100%22><rect width=%22100%22 height=%22100%22 rx=%2250%22 fill=%22%23a2ffed%22></rect><text x=%2250%%22 y=%2250%%22 dominant-baseline=%22central%22 text-anchor=%22middle%22 font-size=%2278%22>🥘</text></svg>" />
    <title>Secret Recipe Box
    </title>
</head>
<body>
    <ul class="nav">
        <li class="nav-link">
            <a href="{{url_for('core.index')}}">Home</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('core.info')}}">About</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-link">
            <a href="{{url_for('recipe_posts.create_recipe')}}">Create Recipe</a> 
        </li>
        <li class="nav-link">
            <a href="{{url_for('users.account')}}">Account</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('users.logout')}}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-link">
            <a href="{{url_for('users.login')}}">Log In</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('users.register')}}">Register</a>
        </li>
        {% endif %}
    </ul>

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

myapp/templates/create_recipe.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{url_for('static', filename='./styles/login.css')}}"/>
<link rel="stylesheet" href="{{url_for('static', filename='./styles/index.css')}}"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&family=Josefin+Slab:wght@600&display=swap" rel="stylesheet">
    <div class="container">
      <form class="form-group create-recipe" method="POST">
          {{form.hidden_tag()}}

          <div class="form-group">
              {{form.title.label(class="form-control-label")}}
              {{form.title(class="form-control form-control-lg")}}
          </div>
          <div class="form-group">
            {{form.text.label(class="form-control-label")}}
            {{form.text(class="form-control form-control-lg")}}
        </div>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
        </div>
      </form>
    </div>
{% endblock %}

myapp/templates/index.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{url_for('static', filename='./styles/index.css')}}"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&family=Josefin+Slab:wght@600&display=swap" rel="stylesheet">
    <div class="jumbotron">
        <h1>Secret Recipe Box</h1>
    </div>
    <div class="container">
        {% for post in recipe_posts.items %}
            <div class="card">
                <div class="card-body">
                    <h2 class="card-text">
                        <a class="card-title" href="{{url_for('recipe_posts.recipe_post', recipe_post_id=post.id)}}">{{post.title}}</a>
                        <a href="{{url_for('users.user_posts', username=post.author.username)}}">Written by: {{post.author.username}}</a>
                    </h2>
                    <p>Published on: {{post.date.strftime('%Y - %m - %d')}}</p>
                    <a class="btn btn-primary" href="{{url_for('recipe_posts.recipe_post', recipe_post_id=post.id)}}">Learn the recipe</a>
                </div>
            </div>
        {% endfor %}
    </div>

    <nav aria-label="Page Navigation example">
        <ul class="pagination justify-content-center">
            {% for page_num in recipe_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if recipe_posts.page == page_num %}
                <li class="page-item disabled">
                    <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{ page_num }}</a>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>
{% endblock %}

myapp/templates/info.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{url_for('static', filename='./styles/index.css')}}"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&family=Josefin+Slab:wght@600&display=swap" rel="stylesheet">
    <div class="about">
        <h1 >What is Secret Recipe Box?</h1>
        <p class="description">Secret Recipe Box is a blog where you can share your favorite recipes and the stories behind them! Have any recipes family and friends can't get enough of? Share it here!</p>
    </div>

{% endblock %}

myapp/templates/login.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{url_for('static', filename='./styles/login.css')}}"/>
<link rel="stylesheet" href="{{url_for('static', filename='./styles/index.css')}}"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&family=Josefin+Slab:wght@600&display=swap" rel="stylesheet">

<form method="POST" class="login-form">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.submit()}}

</form>
{% endblock %}

myapp/templates/recipe_post.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{url_for('static', filename='./styles/index.css')}}"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&family=Josefin+Slab:wght@600&display=swap" rel="stylesheet">
<div class="recipe-card">
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
  {% if post.author == current_user %}
    <div class="recipe-btns">
      <a class="btn btn-secondary" href="{{ url_for('recipe_posts.update', recipe_post_id=post.id) }}">Update</a>
      <br>
      <form action="{{ url_for('recipe_posts.delete_post', recipe_post_id=post.id) }}" method="POST">
        <input class="btn btn-danger" type="submit" value="Delete">
      </form>
    </div>
  {% endif %}
</div>
{% endblock content %}

myapp/templates/register.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{url_for('static', filename='./styles/login.css')}}"/>
<link rel="stylesheet" href="{{url_for('static', filename='./styles/index.css')}}"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&family=Josefin+Slab:wght@600&display=swap" rel="stylesheet">
<form method="POST" class="register">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.username.label}}{{form.username}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.pass_confirm.label}}{{form.pass_confirm}}<br>
    {{form.submit()}}
</form>
{% endblock %}

myapp/templates/user_recipe_posts.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{url_for('static', filename='./styles/index.css')}}"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&family=Josefin+Slab:wght@600&display=swap" rel="stylesheet">
    <div class="container">
        <div class="jumbotron">
            <div align="center">
                <h1>{{user.username}}'s Recipes</h1>
            </div>
        </div>
    {% for post in recipe_posts.items %}
    <div class="card">
      <h2 class="card-style">
          <a href="{{url_for('recipe_posts.recipe_post', recipe_post_id=post.id)}}">{{post.title}}</a>
      </h2>
      Written By: <a href="{{url_for('users.user_posts', username=post.author.username)}}">{{post.author.username}}</a>

      <p class="text-muted">
        Published On: {{post.date.strftime("%y-%m-%d")}}
      </p>
      <br>
      <p>{{post.text}}</p>
      <br>
    </div>
    {% endfor %}
    </div>

    <nav aria-label="Page Navigation example">
        <ul class="pagination justify-content-center">

            {% for page_num in recipe_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if recipe_posts.page == page_num %}
                <li class="page-item disabled">
                    <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>


{% endblock %}